name: dartly
description: >-
  Dartly is a set of extension and functions for Dart that makes your life
   easier and more convenient.
version: 1.0.0
homepage: https://github.com/gsmental/dartly

environment:
  sdk: '>=2.17.3 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
